using MyJetWallet.Circle.Settings.Domain;
using System.Collections.Generic;

namespace MyJetWallet.Circle.Settings.Services
{
    public class CircleWireCountriesService : ICircleWireCountriesService
    {
        private readonly IReadOnlyCollection<BankAccountCountry> _supportedCountries = new BankAccountCountry[]
        {
            new BankAccountCountry() { CountryName = "Brazil", Alpha2Code = "BR", Alpha3Code = "BRA", Numeric = 76, BankAccountType = BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Bulgaria", Alpha2Code = "BG", Alpha3Code = "BGR", Numeric = 100, BankAccountType =    BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Burkina Faso", Alpha2Code = "BF", Alpha3Code = "BFA", Numeric = 854, BankAccountType =        BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Cambodia", Alpha2Code = "KH", Alpha3Code = "KHM", Numeric = 116, BankAccountType =    BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Cameroon", Alpha2Code = "CM", Alpha3Code = "CMR", Numeric = 120, BankAccountType =    BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Canada", Alpha2Code = "CA", Alpha3Code = "CAN", Numeric = 124, BankAccountType =  BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Cayman Islands", Alpha2Code = "KY", Alpha3Code = "CYM", Numeric = 136, BankAccountType =            BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Chad", Alpha2Code = "TD", Alpha3Code = "TCD", Numeric = 148, BankAccountType = BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Chile", Alpha2Code = "CL", Alpha3Code = "CHL", Numeric = 152, BankAccountType =   BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Croatia", Alpha2Code = "HR", Alpha3Code = "HRV", Numeric = 191, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Denmark", Alpha2Code = "DK", Alpha3Code = "DNK", Numeric = 208, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Estonia", Alpha2Code = "EE", Alpha3Code = "EST", Numeric = 233, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Finland", Alpha2Code = "FI", Alpha3Code = "FIN", Numeric = 246, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "France", Alpha2Code = "FR", Alpha3Code = "FRA", Numeric = 250, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Germany", Alpha2Code = "DE", Alpha3Code = "DEU", Numeric = 276, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Gibraltar", Alpha2Code = "GI", Alpha3Code = "GIB", Numeric = 292, BankAccountType =   BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Greece", Alpha2Code = "GR", Alpha3Code = "GRC", Numeric = 300, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Guam", Alpha2Code = "GU", Alpha3Code = "GUM", Numeric = 316, BankAccountType = BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Guatemala", Alpha2Code = "GT", Alpha3Code = "GTM", Numeric = 320, BankAccountType =   BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Guernsey", Alpha2Code = "GG", Alpha3Code = "GGY", Numeric = 831, BankAccountType =    BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Holy See", Alpha2Code = "VA", Alpha3Code = "VAT", Numeric = 336, BankAccountType =          BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Hong Kong", Alpha2Code = "HK", Alpha3Code = "HKG", Numeric = 344, BankAccountType =       BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Hungary", Alpha2Code = "HU", Alpha3Code = "HUN", Numeric = 348, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Iceland", Alpha2Code = "IS", Alpha3Code = "ISL", Numeric = 352, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "India", Alpha2Code = "IN", Alpha3Code = "IND", Numeric = 356, BankAccountType =   BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Indonesia", Alpha2Code = "ID", Alpha3Code = "IDN", Numeric = 360, BankAccountType =       BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Ireland", Alpha2Code = "IE", Alpha3Code = "IRL", Numeric = 372, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Isle of Man", Alpha2Code = "IM", Alpha3Code = "IMN", Numeric = 833, BankAccountType =         BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Israel", Alpha2Code = "IL", Alpha3Code = "ISR", Numeric = 376, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Italy", Alpha2Code = "IT", Alpha3Code = "ITA", Numeric = 380, BankAccountType = BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Japan", Alpha2Code = "JP", Alpha3Code = "JPN", Numeric = 392, BankAccountType =   BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Jersey", Alpha2Code = "JE", Alpha3Code = "JEY", Numeric = 832, BankAccountType =  BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Jordan", Alpha2Code = "JO", Alpha3Code = "JOR", Numeric = 400, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Kenya", Alpha2Code = "KE", Alpha3Code = "KEN", Numeric = 404, BankAccountType =   BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Korea (the Democratic People's Republic of)", Alpha2Code = "KP", Alpha3Code = "PRK", Numeric = 408,          BankAccountType = BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Korea (the Republic of)", Alpha2Code = "KR", Alpha3Code = "KOR", Numeric = 410, BankAccountType =            BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Latvia", Alpha2Code = "LV", Alpha3Code = "LVA", Numeric = 428, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Liechtenstein", Alpha2Code = "LI", Alpha3Code = "LIE", Numeric = 438, BankAccountType =       BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Lithuania", Alpha2Code = "LT", Alpha3Code = "LTU", Numeric = 440, BankAccountType =   BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Luxembourg", Alpha2Code = "LU", Alpha3Code = "LUX", Numeric = 442, BankAccountType =      BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Madagascar", Alpha2Code = "MG", Alpha3Code = "MDG", Numeric = 450, BankAccountType =      BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Malawi", Alpha2Code = "MW", Alpha3Code = "MWI", Numeric = 454, BankAccountType =  BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Malaysia", Alpha2Code = "MY", Alpha3Code = "MYS", Numeric = 458, BankAccountType =    BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Malta", Alpha2Code = "MT", Alpha3Code = "MLT", Numeric = 470, BankAccountType = BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Mexico", Alpha2Code = "MX", Alpha3Code = "MEX", Numeric = 484, BankAccountType =  BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Monaco", Alpha2Code = "MC", Alpha3Code = "MCO", Numeric = 492, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Mozambique", Alpha2Code = "MZ", Alpha3Code = "MOZ", Numeric = 508, BankAccountType =      BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Netherlands (the)", Alpha2Code = "NL", Alpha3Code = "NLD", Numeric = 528, BankAccountType =           BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "New Zealand", Alpha2Code = "NZ", Alpha3Code = "NZL", Numeric = 554, BankAccountType =         BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Niger (the)", Alpha2Code = "NE", Alpha3Code = "NER", Numeric = 562, BankAccountType =         BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Norway", Alpha2Code = "NO", Alpha3Code = "NOR", Numeric = 578, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Peru", Alpha2Code = "PE", Alpha3Code = "PER", Numeric = 604, BankAccountType = BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Philippines", Alpha2Code = "PH", Alpha3Code = "PHL", Numeric = 608, BankAccountType =         BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Poland", Alpha2Code = "PL", Alpha3Code = "POL", Numeric = 616, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Portugal", Alpha2Code = "PT", Alpha3Code = "PRT", Numeric = 620, BankAccountType =    BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Puerto Rico", Alpha2Code = "PR", Alpha3Code = "PRI", Numeric = 630, BankAccountType =         BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Romania", Alpha2Code = "RO", Alpha3Code = "ROU", Numeric = 642, BankAccountType =     BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "San Marino", Alpha2Code = "SM", Alpha3Code = "SMR", Numeric = 674, BankAccountType =      BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Senegal", Alpha2Code = "SN", Alpha3Code = "SEN", Numeric = 686, BankAccountType =     BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Singapore", Alpha2Code = "SG", Alpha3Code = "SGP", Numeric = 702, BankAccountType =       BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Slovakia", Alpha2Code = "SK", Alpha3Code = "SVK", Numeric = 703, BankAccountType =    BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Slovenia", Alpha2Code = "SI", Alpha3Code = "SVN", Numeric = 705, BankAccountType =    BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "South Africa", Alpha2Code = "ZA", Alpha3Code = "ZAF", Numeric = 710, BankAccountType =        BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Spain", Alpha2Code = "ES", Alpha3Code = "ESP", Numeric = 724, BankAccountType = BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Sweden", Alpha2Code = "SE", Alpha3Code = "SWE", Numeric = 752, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Switzerland", Alpha2Code = "CH", Alpha3Code = "CHE", Numeric = 756, BankAccountType =         BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Taiwan (Province of China)", Alpha2Code = "TW", Alpha3Code = "TWN", Numeric = 158, BankAccountType =         BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Tanzania", Alpha2Code = "TZ", Alpha3Code = "TZA", Numeric = 834, BankAccountType =    BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Thailand", Alpha2Code = "TH", Alpha3Code = "THA", Numeric = 764, BankAccountType =    BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Turkey", Alpha2Code = "TR", Alpha3Code = "TUR", Numeric = 792, BankAccountType =  BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "United Arab Emirates (the)", Alpha2Code = "AE", Alpha3Code = "ARE", Numeric = 784, BankAccountType =         BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "United Kingdom of Great Britain and Northern Ireland (the)", Alpha2Code = "GB", Alpha3Code = "GBR",   Numeric    =     826, BankAccountType = BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "United States Minor Outlying Islands (the)", Alpha2Code = "UM", Alpha3Code = "UMI", Numeric = 581,           BankAccountType = BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "United States of America (the)", Alpha2Code = "US", Alpha3Code = "USA", Numeric = 840, BankAccountType    =      BankAccountType.US },
            new BankAccountCountry() { CountryName = "Uzbekistan", Alpha2Code = "UZ", Alpha3Code = "UZB", Numeric = 860, BankAccountType =      BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Viet Nam", Alpha2Code = "VN", Alpha3Code = "VNM", Numeric = 704, BankAccountType =    BankAccountType.SWIFT },
            new BankAccountCountry() { CountryName = "Virgin Islands (British)", Alpha2Code = "VG", Alpha3Code = "VGB", Numeric = 92, BankAccountType =            BankAccountType.SEPA },
            new BankAccountCountry() { CountryName = "Virgin Islands (U.S.)", Alpha2Code = "VI", Alpha3Code = "VIR", Numeric = 850, BankAccountType = BankAccountType.SWIFT },
        };
        public IReadOnlyCollection<BankAccountCountry> GetAllSupportedCountries()
        {
            return _supportedCountries;
        }
    }
}